# Ensure reset_gpio is present before WiFi SDIO stack
softdep rtw88_8821cs pre: reset_gpio rtw88_8821c rtw88_sdio rtw88_core mac80211 cfg80211 rfkill
softdep rtw88_sdio pre: reset_gpio
softdep hci_uart pre: bluetooth btrtl
