adjust_kernel_files="yes"

adjust_kernel_files_cmd() {
    install -Dm644 "${tag_rootfs}/usr/lib/lpa3399pro/rk3399pro-neardi-linux-lc110-base.dtb" \
        "${tag_bootfs}/dtb/rockchip/rk3399pro-neardi-linux-lc110-base.dtb"
}
